version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1420:1420"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
